-- Datos iniciales del catalogo MVP. No contiene historial ni timers.
PRAGMA foreign_keys = ON;

INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (1, 'Beelzebub', 720, 730, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (2, 'Ifrit', 660, 670, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (3, 'Valkyrie Randgris', 480, 490, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (4, 'Wounded Morroc', 720, 780, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (5, 'High Priest Margaretha', 100, 130, 'lhz_dun03_bio3');
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (6, 'High Wizard Kathryne', 100, 130, 'lhz_dun03_bio3');
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (7, 'Assassin Cross Eremes', 100, 130, 'lhz_dun03_bio3');
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (8, 'Sniper Cecil', 100, 130, 'lhz_dun03_bio3');
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (9, 'Lord Knight Seyren', 100, 130, 'lhz_dun03_bio3');
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (10, 'Whitesmith Howard', 100, 130, 'lhz_dun03_bio3');
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (11, 'Nidhoggr''s Shadow', 720, 720, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (12, 'Detardeurus', 180, 190, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (13, 'Atroce', 180, 370, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (14, 'RSX-0806', 125, 135, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (15, 'Stormy Knight', 60, 70, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (16, 'Orc Lord', 120, 130, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (17, 'Orc Hero', 60, 1450, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (18, 'Phreeoni', 120, 130, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (19, 'Maya', 120, 130, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (20, 'Moonlight Flower', 60, 70, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (21, 'Egnigem Cenia', 120, 130, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (22, 'Evil Snake Lord', 94, 104, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (23, 'Gopinich', 120, 130, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (24, 'Lord of the Dead', 133, 133, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (25, 'Hatii', 120, 130, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (26, 'Dark Lord', 60, 70, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (27, 'Dracula', 60, 70, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (28, 'Doppelganger', 120, 130, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (29, 'Mistress', 120, 130, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (30, 'Golden Thief Bug', 60, 70, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (31, 'Pharaoh', 60, 70, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (32, 'Amon Ra', 60, 70, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (33, 'Baphomet', 120, 130, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (34, 'Turtle General', 60, 70, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (35, 'Drake', 120, 130, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (36, 'Fallen Bishop Hibram', 120, 130, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (37, 'Thanatos', 720, 720, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (38, 'Gloom Under Night', 300, 310, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (39, 'Boitata', 120, 130, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (40, 'Eddga', 120, 130, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (41, 'Kiel D-01', 120, 180, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (42, 'Incantation Samurai', 91, 101, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (43, 'Samurai Specter', 91, 101, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (44, 'Osiris', 60, 70, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (45, 'Lady Tanee', 420, 430, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (46, 'Bacsojin', 117, 127, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (47, 'White Lady', 117, 127, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (48, 'Iara', 120, 150, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (49, 'Vesper', 120, 130, NULL);
INSERT INTO mvp_definitions (id, name, respawn_min_minutes, respawn_max_minutes, shared_spawn_group) VALUES (50, 'Tao Gunka', 300, 310, NULL);

INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (1, 1, 'abbey03', 720, 730, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (2, 2, 'thor_v03', 660, 670, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (3, 3, 'odin_tem03', 480, 490, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (4, 4, 'moc_fild22', 720, 780, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (5, 5, 'lhz_dun03', 100, 130, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (6, 6, 'lhz_dun03', 100, 130, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (7, 7, 'lhz_dun03', 100, 130, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (8, 8, 'lhz_dun03', 100, 130, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (9, 9, 'lhz_dun03', 100, 130, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (10, 10, 'lhz_dun03', 100, 130, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (11, 11, '2@nyd', 720, 720, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (12, 12, 'abyss_03', 180, 190, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (13, 13, 'ra_fild02', 240, 250, 1, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (14, 13, 'ra_fild03', 180, 190, 1, 1);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (15, 13, 'ra_fild04', 300, 310, 1, 2);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (16, 13, 've_fild01', 180, 190, 1, 3);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (17, 13, 've_fild02', 360, 370, 1, 4);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (18, 14, 'ein_dun02', 125, 135, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (19, 15, 'xmas_dun02', 60, 70, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (20, 16, 'gef_fild10', 120, 130, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (21, 17, 'gef_fild14', 60, 70, 1, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (22, 17, 'gef_fild10', 1440, 1450, 1, 1);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (23, 18, 'moc_fild17', 120, 130, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (24, 19, 'anthell02', 120, 130, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (25, 20, 'pay_dun04', 60, 70, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (26, 21, 'lhz_dun02', 120, 130, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (27, 22, 'gon_dun03', 94, 104, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (28, 23, 'mosk_dun03', 120, 130, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (29, 24, 'niflheim', 133, 133, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (30, 25, 'xmas_fild01', 120, 130, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (31, 26, 'gl_chyard', 60, 70, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (32, 27, 'gef_dun01', 60, 70, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (33, 28, 'gef_dun02', 120, 130, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (34, 29, 'mjolnir_04', 120, 130, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (35, 30, 'prt_sewb4', 60, 70, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (36, 31, 'in_sphinx5', 60, 70, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (37, 32, 'moc_pryd06', 60, 70, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (38, 33, 'prt_maze03', 120, 130, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (39, 34, 'tur_dun04', 60, 70, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (40, 35, 'treasure02', 120, 130, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (41, 36, 'abbey02', 120, 130, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (42, 37, 'thana_t12', 720, 720, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (43, 38, 'ra_san05', 300, 310, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (44, 39, 'bra_dun02', 120, 130, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (45, 40, 'pay_fild11', 120, 130, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (46, 41, 'kh_dun02', 120, 180, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (47, 42, 'ama_dun03', 91, 101, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (48, 43, 'ama_dun03', 91, 101, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (49, 44, 'moc_pryd04', 60, 70, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (50, 45, 'ayo_dun02', 420, 430, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (51, 46, 'lou_dun03', 117, 127, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (52, 47, 'lou_dun03', 117, 127, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (53, 48, 'iz_dun05', 120, 150, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (54, 49, 'jupe_core', 120, 130, 0, 0);
INSERT INTO mvp_maps (id, mvp_id, map_name, respawn_min_minutes, respawn_max_minutes, is_override, position) VALUES (55, 50, 'beach_dun', 300, 310, 0, 0);

